version: "3.9"

services:
  mqtt_backend:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_backend
    ports:
      - "1883:1883"   # MQTT
      - "9001:9001"   # WebSockets (optional)
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

    restart: unless-stopped

  backend:
    build: ./webapp
    container_name: webapp
    environment:
      - MQTT_HOST=mqtt_backend
      - MQTT_PORT=1883
    depends_on:
      - mqtt_backend
    ports:
      - "8080:8080"
